--drop table events cascade;

--drop table categories cascade;

--drop table location cascade;

--drop table price cascade;

--drop table users cascade;

CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(60)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS location
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lap         FLOAT                                   NOT NULL,
    lon         FLOAT                                   NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS price
(
    paid_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    paid    BOOLEAN                                 NOT NULL,
    price   FLOAT                                   NOT NULL,
    CONSTRAINT pk_paid PRIMARY KEY (paid_id)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_annotation  VARCHAR(255)                            NOT NULL,
    event_description VARCHAR(512)                            NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    conformed_requests INT                                     NOT NULL,
    participant_limit  INT                                     NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_data         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    request_moderation TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    paid_id            BIGINT                                  NOT NULL,
    state              VARCHAR(50)                             NOT NULL,
    title              VARCHAR(200)                            NOT NULL,
    views              VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (event_id),
    CONSTRAINT fk_category_id_events FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT fk_location_id_events FOREIGN KEY (location_id) REFERENCES location (location_id),
    CONSTRAINT fk_user_id_events FOREIGN KEY (initiator_id) REFERENCES users (user_id),
    CONSTRAINT fk_paid_id_events FOREIGN KEY (paid_id) REFERENCES price (paid_id)
);