version: '3.1'
services:

  stats-server:
    build: stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_SERVICE_URL=http://localhost:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ewm-service
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - STATS-SERVER_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmservice

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmservice
      - POSTGRES_USER=ewmservice
      - POSTGRES_PASSWORD=ewmservice