--drop table stats cascade;

CREATE TABLE IF NOT EXISTS stats
(
    stats_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hits       BIGINT                                  NOT NULL,
    app        VARCHAR(255)                            NOT NULL,
    uri        VARCHAR(512)                            NOT NULL,
    ip         BIGINT                                  NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (stats_id)
);